#Random Librery
import random
import os

#Global Constants
equals = ("=========================================")
big = ("\n|--- Try again, the number is big. ")
small = ("\n|--- Try again, the number is small. ")
close = ("You're close ---|\n")
far = ("You're far ---|\n")
clear = lambda: os.system('cls')

def guessnumber(x, y):
    random = x
    limit = y
    number = 0
    attemps = 0

    print(random)

    while number != random:

        print(f"Attemps: {attemps}")
        number = int(input(f"Please, choose a number between 1 and {limit}: "))
        
        if number > random:
            attemps += 1
            substact = number - random
            if substact < 10:
                print(big + close)
            else:
                print(big + far)
        else:
            attemps += 1
            substact = random - number
            if substact < 10:
                print(small + close)
            else:
                print(small + far)
    
    clear()
    print(equals)
    print("|-------------CONGRATULATIONS-----------|")
    print(f"{equals}\n")

    print(f"|--- You guessed the number '{random}' in just {attemps} attempts ---|")
    input('\nPress any key to continue...')
    main()

def menu(op):
    if op == 1:
        clear()
        print(equals)
        print("|------------GUESS THE NUMBER-----------|")
        print(f"{equals}\n\n")

        number_limit = int(input("Please, choose a number greater than 1: "))
        random_number = random.randint(1, number_limit)
        print()
        guessNumber(random_number, number_limit)

    elif op == 2:
        clear()
        print(equals)
        print("|--------------INSTRUCCIONS-------------|")
        print(f"{equals}\n\n")

        print("Your goal is to guess the number generated by the computer. How? It's very simple.")
        print("The computer will generate a number between the number 1 to X number.")
        print("The number X will be a number chosen by the user to assign a limit. \n\n")

        print("Then you should try to guess the number and in each attempt the game will")
        print('give you a clue if you are near or far from the number.\n\n')

        print(equals)
        print("|---------------GOOD LUCK!--------------|")
        print(f"{equals}\n")

        input('Press any key to continue...')
        menu(1)

    elif op == 3:
        clear()
        print("\n|---- Thanks for playing :D ---|\n\n")
        quit()

def main():
    clear()
    print(equals)
    print("|-----Welcome to 'Guess the Number'-----|")
    print(f"{equals}\n")

    print("1. Play")
    print("2. Instruccions")
    print("3. Exit")

    option = int(input("\nPlease choose a option to continue: "))
    
    menu(option)

main()