#Random Librery
import random
import os

#Global Constants
equals = ("=========================================")
clear = lambda: os.system('cls')

def guessNumber(x):
    return

def menu(op):
    if op == 1:
        clear()
        print(equals)
        print("|------------GUESS THE NUMBER-----------|")
        print(f"{equals}\n\n")

        guessNumber(15)
    elif op == 2:
        clear()
        print(equals)
        print("|--------------INSTRUCCIONS-------------|")
        print(f"{equals}\n\n")

        print("Your goal is to guess the number generated by the computer. How? It's very simple.")
        print("The computer will generate a number between the number 1 to X number.")
        print("Number X will also be generated by the computer to put a limit. \n\n")

        print("Then you should try to guess the number and in each attempt the game will")
        print('give you a clue if you are near or far from the number.\n\n')

        print(equals)
        print("|---------------GOOD LUCK!--------------|")
        print(f"{equals}\n")

        input('Press any key to continue...')
        menu(1)

    elif op == 3:
        quit()

def main():
    clear()
    print(equals)
    print("|-----Welcome to 'Guess the Number'-----|")
    print(f"{equals}\n")

    print("1. Play")
    print("2. Instruccions")
    print("3. Exit")

    option = int(input("\nPlease choose a option to continue: "))
    
    menu(option)

main()