#Random Librery
import random
import os

#Constants
equals = ("=========================================")
big = ("\n|--- Try again, the number is big. ")
small = ("\n|--- Try again, the number is small. ")
close = ("You're close ---|\n")
far = ("You're far ---|\n")
#To clear the terminal
clear = lambda: os.system('cls')

#Function game base
def guessnumber(x, y):

    clear()
    print(equals)
    print("|------------GUESS THE NUMBER-----------|")
    print(f"{equals}\n\n")

    #Constants that save the values
    random = x
    limit = y
    number = 0

    #Attempt counter
    attemps = 0

    #True until both numbers are equal
    while number != random:

        print(f"Attemps: {attemps}")
        number = int(input(f"Please, choose a number between 1 and {limit}: "))
        
        #If the number is greater than the generated
        if number > random:
            attemps += 1
            substact = number - random

            #If the number is close or far than the generated
            if substact < 10:
                print(big + close)
            else:
                print(big + far)

        #If the number is less than the generated
        else:
            attemps += 1
            substact = random - number

            #If the number is close or far than the generated
            if substact < 10:
                print(small + close)
            else:
                print(small + far)
    
    clear()
    print(equals)
    print("|-------------CONGRATULATIONS-----------|")
    print(f"{equals}\n")

    print(f"|--- You guessed the number '{random}' in just {attemps} attempts ---|")
    input('\nPress any key to continue...')
    main()

def menu(op):

    if op == 1:
        clear()

        while True:

            print(equals)
            print("|------------GUESS THE NUMBER-----------|")
            print(f"{equals}\n\n")

            try:
                #Assigned limit by the user
                number_limit = int(input("Please, choose a number greater than 1: "))
                
                #Generated the number
                random_number = random.randint(1, number_limit)

                #Sending the values
                guessnumber(random_number, number_limit)
                
            except (ValueError, TypeError, IndexError):
                print("\n|--- ERROR: The data entered is invalid ---|\n")

    elif op == 2:

        clear()

        print(equals)
        print("|--------------INSTRUCCIONS-------------|")
        print(f"{equals}\n\n")

        print("Your goal is to guess the number generated by the computer. How? It's very simple.")
        print("The computer will generate a number between the number 1 to X number.")
        print("The number X will be a number chosen by the user to assign a limit. \n\n")

        print("Then you should try to guess the number and in each attempt the game will")
        print('give you a clue if you are near or far from the number.\n\n')

        print(equals)
        print("|---------------GOOD LUCK!--------------|")
        print(f"{equals}\n")

        input('Press any key to continue...')
        menu(1)

    elif op == 3:

        clear()

        print("\n|---- Thanks for playing :D ---|\n\n")
        quit()

def main():

    clear()

    while True:  
          
        print(equals)
        print("|-----Welcome to 'Guess the Number'-----|")
        print(f"{equals}\n")

        try:
            print("1. Play")
            print("2. Instruccions")
            print("3. Exit")

            option = int(input("\nPlease choose a option to continue: "))

            if option < 1 or option > 3:
                print("\n|--- ERROR: The option entered is invalid ---|\n")

        except (ValueError, TypeError, IndexError):
            print("\n|--- ERROR: The data entered is invalid ---|\n")

        finally:
            menu(option)

main()